# Generated by Django 5.2.12 on 2026-06-02 21:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="número"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando pagamento"),
                            ("paid", "Pago"),
                            ("processing", "Em produção"),
                            ("shipped", "Enviado"),
                            ("delivered", "Entregue"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("pix", "PIX"),
                            ("credit_card", "Cartão de crédito"),
                            ("boleto", "Boleto"),
                        ],
                        max_length=12,
                        verbose_name="método",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("refused", "Recusado"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status do pagamento",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="pago em"),
                ),
                (
                    "card_last4",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="cartão (final)"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="desconto",
                    ),
                ),
                (
                    "shipping",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="frete",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="total",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(blank=True, max_length=30, verbose_name="cupom"),
                ),
                (
                    "recipient",
                    models.CharField(max_length=120, verbose_name="destinatário"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                ("zip_code", models.CharField(max_length=9, verbose_name="CEP")),
                ("street", models.CharField(max_length=160, verbose_name="logradouro")),
                ("number_addr", models.CharField(max_length=20, verbose_name="número")),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="complemento"
                    ),
                ),
                ("district", models.CharField(max_length=80, verbose_name="bairro")),
                ("city", models.CharField(max_length=80, verbose_name="cidade")),
                ("state", models.CharField(max_length=2, verbose_name="UF")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=140, verbose_name="produto"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="preço unitário"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="quantidade")),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total da linha"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "item do pedido",
                "verbose_name_plural": "itens do pedido",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["number"], name="orders_orde_number_539d36_idx"),
        ),
    ]
