# Generated by Django 5.2.12 on 2026-06-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='draft_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='rascunho lithophane'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='litho_specs',
            field=models.JSONField(blank=True, null=True, verbose_name='specs do lithophane'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando pagamento'), ('paid', 'Pago'), ('processing', 'Em produção'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('orcamento', 'Orçamento pendente')], default='pending', max_length=12, verbose_name='status'),
        ),
    ]
