# Generated by Django 5.2.12 on 2026-06-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="document",
            field=models.CharField(blank=True, max_length=20, verbose_name="CPF/CNPJ"),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("cliente", "Cliente"), ("vendedor", "Vendedor")],
                default="cliente",
                max_length=10,
                verbose_name="papel",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="store_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="nome da loja"
            ),
        ),
    ]
