# Generated by Django 5.2.12 on 2026-06-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_document_user_role_user_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store_name',
        ),
    ]
