# Generated by Django 5.2.12 on 2026-06-16 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='token público')),
                ('cliente_nome', models.CharField(max_length=120, verbose_name='nome do cliente')),
                ('peca_descricao', models.CharField(max_length=240, verbose_name='descrição da peça')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('prazo_entrega', models.CharField(max_length=80, verbose_name='prazo de entrega')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
            },
        ),
    ]
