# Generated by Django 5.2.12 on 2026-06-02 21:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="código"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percentual (%)"),
                            ("fixed", "Valor fixo (R$)"),
                        ],
                        default="percent",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor"
                    ),
                ),
                (
                    "min_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="pedido mínimo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="válido de"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="válido até"
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="limite de usos"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="usos"),
                ),
            ],
            options={
                "verbose_name": "cupom",
                "verbose_name_plural": "cupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hero", "Destaque (home)"),
                            ("strip", "Faixa"),
                            ("banner", "Banner"),
                        ],
                        default="strip",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="título")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="subtítulo"
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        default="Oferta", max_length=40, verbose_name="selo"
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        default="Conferir", max_length=40, verbose_name="texto do botão"
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        default="/catalogo/",
                        max_length=200,
                        verbose_name="link do botão",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="promotions/", verbose_name="imagem"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="início"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="fim"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordem")),
            ],
            options={
                "verbose_name": "promoção",
                "verbose_name_plural": "promoções",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
