# Generated by Django 5.2.12 on 2026-06-08 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productimage_review_product_is_on_promotion_and_more"),
        ("promotions", "0002_promotion_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor original"
                    ),
                ),
                (
                    "promo_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="valor promocional",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="inicio"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="fim"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordem")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="catalog.category",
                        verbose_name="categoria",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="catalog.product",
                        verbose_name="produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "oferta",
                "verbose_name_plural": "ofertas",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="promotions__is_acti_024c43_idx",
                    ),
                    models.Index(
                        fields=["category", "is_active"],
                        name="promotions__categor_43a713_idx",
                    ),
                ],
            },
        ),
    ]
