# Generated by Django 5.2.12 on 2026-06-07 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LithophaneDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='sessão')),
                ('image', models.ImageField(upload_to='lithophane/fotos/', verbose_name='foto enviada')),
                ('model_glb', models.FileField(blank=True, upload_to='lithophane/glb/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb'])], verbose_name='modelo GLB')),
                ('model_stl', models.FileField(blank=True, upload_to='lithophane/stl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])], verbose_name='arquivo STL')),
                ('format', models.CharField(choices=[('placa', 'Placa plana'), ('luminaria', 'Luminária'), ('curvo', 'Curvo'), ('cubo', 'Cubo')], default='placa', max_length=12, verbose_name='formato')),
                ('size', models.DecimalField(decimal_places=1, default=100.0, max_digits=6, verbose_name='tamanho (mm)')),
                ('thickness', models.DecimalField(decimal_places=1, default=3.0, max_digits=4, verbose_name='espessura máx (mm)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lithophane_drafts', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'rascunho de lithophane',
                'verbose_name_plural': 'rascunhos de lithophane',
                'ordering': ['-created_at'],
            },
        ),
    ]
