# Generated by Django 5.2.12 on 2026-06-02 21:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="nome"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=90, unique=True, verbose_name="slug"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="cube",
                        help_text="Nome do ícone SVG do sprite (ex.: cube, tag, bolt, box, layers).",
                        max_length=20,
                        verbose_name="ícone",
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex usado no card e no placeholder da categoria.",
                        max_length=7,
                        verbose_name="cor de destaque",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "is_highlighted",
                    models.BooleanField(default=True, verbose_name="destaque na home"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordem")),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("name", models.CharField(max_length=140, verbose_name="nome")),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="preço"
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço antigo riscado. Deixe vazio se não houver desconto.",
                        max_digits=10,
                        null=True,
                        verbose_name="preço cheio",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="products/", verbose_name="imagem"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=10, verbose_name="estoque"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.0"),
                        max_digits=3,
                        verbose_name="avaliação",
                    ),
                ),
                (
                    "sales_count",
                    models.PositiveIntegerField(default=0, verbose_name="vendas"),
                ),
                (
                    "material",
                    models.CharField(
                        default="PLA", max_length=60, verbose_name="material"
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="dimensões"
                    ),
                ),
                (
                    "print_time_hours",
                    models.PositiveIntegerField(
                        default=4, verbose_name="tempo de impressão (h)"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="destaque"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_featured"],
                        name="catalog_pro_is_acti_e6e001_idx",
                    ),
                    models.Index(
                        fields=["category", "is_active"],
                        name="catalog_pro_categor_891fe8_idx",
                    ),
                    models.Index(
                        fields=["-sales_count"], name="catalog_pro_sales_c_9ac6ba_idx"
                    ),
                ],
            },
        ),
    ]
