# Generated by Django 5.2.12 on 2026-06-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Usada quando não há upload. Útil para demo/seed.",
                max_length=500,
                verbose_name="imagem (URL externa)",
            ),
        ),
    ]
