# Generated by Django 5.2.12 on 2026-06-06 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Arquivo .glb ou .gltf exibido no visualizador 3D.', upload_to='products/models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf'])], verbose_name='modelo 3D (GLB/glTF)'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_stl',
            field=models.FileField(blank=True, help_text='Arquivo .stl imprimível, disponibilizado para download.', upload_to='products/stl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])], verbose_name='arquivo STL (impressão)'),
        ),
    ]
