# Generated by Django 5.2.12 on 2026-06-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_model_3d_product_model_stl'),
        ('catalog', '0003_product_seller'),
    ]

    operations = [
    ]
