# Generated by Django 5.2.12 on 2026-06-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_seller_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='imagem')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'imagem da galeria',
                'verbose_name_plural': 'imagens da galeria',
                'ordering': ('order',),
            },
        ),
    ]
