# Generated by Django 5.2.12 — campos de specs de filamento para o Product.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filament_grams',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Consumo total de filamento em gramas extraído do 3MF. 0 = desconhecido.',
                verbose_name='gramas de filamento',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='color_count',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text='Quantidade de cores/filamentos distintos no 3MF.',
                verbose_name='número de cores',
            ),
        ),
    ]
