# Generated by Django 5.2.12 on 2026-06-09 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("text", models.TextField(max_length=500, verbose_name="pergunta")),
                (
                    "answer",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="resposta"
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="respondido em"
                    ),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="respondido por",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="catalog.product",
                        verbose_name="produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "pergunta",
                "verbose_name_plural": "perguntas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="catalog_que_product_b345fc_idx",
                    )
                ],
            },
        ),
    ]
